[project]
name = "global-macro-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dbt-core>=1.10.11",
    "dbt-duckdb>=1.9.4",
]
